package net.yuanmomo.framework.bean;

import java.io.Serializable;
import java.util.Date;

public class Demo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.byteCol
     *
     * @mbggenerated
     */
    private Byte bytecol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.shortCol
     *
     * @mbggenerated
     */
    private Short shortcol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.intCol
     *
     * @mbggenerated
     */
    private Integer intcol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.floatCol
     *
     * @mbggenerated
     */
    private Float floatcol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.doubleCol
     *
     * @mbggenerated
     */
    private Double doublecol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.boolCol
     *
     * @mbggenerated
     */
    private Boolean boolcol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.StringCol1
     *
     * @mbggenerated
     */
    private String stringcol1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.StringCol2
     *
     * @mbggenerated
     */
    private String stringcol2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.dateCol
     *
     * @mbggenerated
     */
    private Date datecol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.blobCol
     *
     * @mbggenerated
     */
    private byte[] blobcol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.byteCol
     *
     * @return the value of demo.byteCol
     *
     * @mbggenerated
     */
    public Byte getBytecol() {
        return bytecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.byteCol
     *
     * @param bytecol the value for demo.byteCol
     *
     * @mbggenerated
     */
    public void setBytecol(Byte bytecol) {
        this.bytecol = bytecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.shortCol
     *
     * @return the value of demo.shortCol
     *
     * @mbggenerated
     */
    public Short getShortcol() {
        return shortcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.shortCol
     *
     * @param shortcol the value for demo.shortCol
     *
     * @mbggenerated
     */
    public void setShortcol(Short shortcol) {
        this.shortcol = shortcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.intCol
     *
     * @return the value of demo.intCol
     *
     * @mbggenerated
     */
    public Integer getIntcol() {
        return intcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.intCol
     *
     * @param intcol the value for demo.intCol
     *
     * @mbggenerated
     */
    public void setIntcol(Integer intcol) {
        this.intcol = intcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.floatCol
     *
     * @return the value of demo.floatCol
     *
     * @mbggenerated
     */
    public Float getFloatcol() {
        return floatcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.floatCol
     *
     * @param floatcol the value for demo.floatCol
     *
     * @mbggenerated
     */
    public void setFloatcol(Float floatcol) {
        this.floatcol = floatcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.doubleCol
     *
     * @return the value of demo.doubleCol
     *
     * @mbggenerated
     */
    public Double getDoublecol() {
        return doublecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.doubleCol
     *
     * @param doublecol the value for demo.doubleCol
     *
     * @mbggenerated
     */
    public void setDoublecol(Double doublecol) {
        this.doublecol = doublecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.boolCol
     *
     * @return the value of demo.boolCol
     *
     * @mbggenerated
     */
    public Boolean getBoolcol() {
        return boolcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.boolCol
     *
     * @param boolcol the value for demo.boolCol
     *
     * @mbggenerated
     */
    public void setBoolcol(Boolean boolcol) {
        this.boolcol = boolcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.StringCol1
     *
     * @return the value of demo.StringCol1
     *
     * @mbggenerated
     */
    public String getStringcol1() {
        return stringcol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.StringCol1
     *
     * @param stringcol1 the value for demo.StringCol1
     *
     * @mbggenerated
     */
    public void setStringcol1(String stringcol1) {
        this.stringcol1 = stringcol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.StringCol2
     *
     * @return the value of demo.StringCol2
     *
     * @mbggenerated
     */
    public String getStringcol2() {
        return stringcol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.StringCol2
     *
     * @param stringcol2 the value for demo.StringCol2
     *
     * @mbggenerated
     */
    public void setStringcol2(String stringcol2) {
        this.stringcol2 = stringcol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.dateCol
     *
     * @return the value of demo.dateCol
     *
     * @mbggenerated
     */
    public Date getDatecol() {
        return datecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.dateCol
     *
     * @param datecol the value for demo.dateCol
     *
     * @mbggenerated
     */
    public void setDatecol(Date datecol) {
        this.datecol = datecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.blobCol
     *
     * @return the value of demo.blobCol
     *
     * @mbggenerated
     */
    public byte[] getBlobcol() {
        return blobcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.blobCol
     *
     * @param blobcol the value for demo.blobCol
     *
     * @mbggenerated
     */
    public void setBlobcol(byte[] blobcol) {
        this.blobcol = blobcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Demo other = (Demo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBytecol() == null ? other.getBytecol() == null : this.getBytecol().equals(other.getBytecol()))
            && (this.getShortcol() == null ? other.getShortcol() == null : this.getShortcol().equals(other.getShortcol()))
            && (this.getIntcol() == null ? other.getIntcol() == null : this.getIntcol().equals(other.getIntcol()))
            && (this.getFloatcol() == null ? other.getFloatcol() == null : this.getFloatcol().equals(other.getFloatcol()))
            && (this.getDoublecol() == null ? other.getDoublecol() == null : this.getDoublecol().equals(other.getDoublecol()))
            && (this.getBoolcol() == null ? other.getBoolcol() == null : this.getBoolcol().equals(other.getBoolcol()))
            && (this.getStringcol1() == null ? other.getStringcol1() == null : this.getStringcol1().equals(other.getStringcol1()))
            && (this.getStringcol2() == null ? other.getStringcol2() == null : this.getStringcol2().equals(other.getStringcol2()))
            && (this.getDatecol() == null ? other.getDatecol() == null : this.getDatecol().equals(other.getDatecol()))
            && (this.getBlobcol() == null ? other.getBlobcol() == null : this.getBlobcol().equals(other.getBlobcol()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBytecol() == null) ? 0 : getBytecol().hashCode());
        result = prime * result + ((getShortcol() == null) ? 0 : getShortcol().hashCode());
        result = prime * result + ((getIntcol() == null) ? 0 : getIntcol().hashCode());
        result = prime * result + ((getFloatcol() == null) ? 0 : getFloatcol().hashCode());
        result = prime * result + ((getDoublecol() == null) ? 0 : getDoublecol().hashCode());
        result = prime * result + ((getBoolcol() == null) ? 0 : getBoolcol().hashCode());
        result = prime * result + ((getStringcol1() == null) ? 0 : getStringcol1().hashCode());
        result = prime * result + ((getStringcol2() == null) ? 0 : getStringcol2().hashCode());
        result = prime * result + ((getDatecol() == null) ? 0 : getDatecol().hashCode());
        result = prime * result + ((getBlobcol() == null) ? 0 : getBlobcol().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bytecol=").append(bytecol);
        sb.append(", shortcol=").append(shortcol);
        sb.append(", intcol=").append(intcol);
        sb.append(", floatcol=").append(floatcol);
        sb.append(", doublecol=").append(doublecol);
        sb.append(", boolcol=").append(boolcol);
        sb.append(", stringcol1=").append(stringcol1);
        sb.append(", stringcol2=").append(stringcol2);
        sb.append(", datecol=").append(datecol);
        sb.append(", blobcol=").append(blobcol);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}