package net.yuanmomo.framework.controller.mybatis;

import com.alibaba.fastjson.JSON;
import java.util.List;
import net.yuanmomo.framework.bean.Test;
import net.yuanmomo.framework.bean.TestParam;
import net.yuanmomo.framework.business.mybatis.TestBusiness;
import net.yuanmomo.util.CollectionUtil;
import net.yuanmomo.util.exception.BaseException;
import net.yuanmomo.util.generator.PaginationBean;
import net.yuanmomo.util.generator.PaginationUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("/test/jsp/")
public class TestController {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test
     *
     * @mbggenerated
     */
    private static Logger logger = LoggerFactory.getLogger(TestController.class);

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test
     *
     * @mbggenerated
     */
    @Autowired 
    private TestBusiness testBusiness;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    @RequestMapping(value = "insert.do")
    public String insert(@ModelAttribute("test")  Test test, ModelMap map) {
        try {
            // 数据校验
            
            if(this.testBusiness.insertSelective(test) == 1){
                map.put("message","插入成功。");
            }else{
                map.put("message","插入失败。");
            }
        } catch (BaseException e1) {
            map.put("message", e1.getKey());
        } catch (Exception e) {
            logger.error("插入异常" + e.getMessage());
            map.put("message","插入异常" + e.getMessage());
        }
        return "out";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    @RequestMapping(value = "getTestByKey.do")
    public String getTestByKey(@RequestParam("id")  Long id, ModelMap map) {
        try {
            if(id == null || id < 0){
                map.put("message","ID 错误。"); 
                return "out";
            }
            Test result = this.testBusiness.getTestByKey(id);
            map.put("message",result);
        } catch (BaseException e1) {
            map.put("message", e1.getKey());
        } catch (Exception e) {
            logger.error("主键获取详情异常;key="+id + e.getMessage());
            map.put("message","主键获取详情异常;key="+id + e.getMessage());
        }
        return "out";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    @RequestMapping(value = "selectTestList.do")
    public String selectTestList(@RequestParam("conditionType")  Short conditionType, @RequestParam("conditionValue")  String conditionValue, @ModelAttribute  PaginationBean paginationBean, ModelMap map) {
        try {
            int currentPage = paginationBean.getPageNum();
            int pageSize = paginationBean.getNumPerPage(); 
            
            if(pageSize < 1){
                map.put("message","pageSize 错误。"); 
                return "out";
            }
            if(currentPage<1){
                map.put("message","currentPage 错误。"); 
                return "out";
            }
            // 构造查询参数
            TestParam param =new TestParam();
            //TestParam.Criteria criteria = param.createCriteria();
            
            // 根据参数设置查询条件
            
            // 取得当前查询的总记录结果
            int total = this.testBusiness.countTestList(param);
            if(total == 0){
                // 没有记录数
                map.put("message","没有记录。"); 
                return "out";
            }
            paginationBean.setTotalCount(total);
            // 判断当前请求的页码有没有超过总页数
            int totalPages = PaginationUtil.getPages(total, pageSize);
            paginationBean.setTotalPages(totalPages);
            
            if(currentPage > totalPages){
                // 当前页超过总页数,取最大数
                currentPage = totalPages;
                paginationBean.setPageNum(currentPage);
            }
            
            // 设置排序
            // param.setOrderByClause(" id asc ");
            
            int start = (currentPage - 1) * pageSize;
            param.setStart(start);
            param.setCount(pageSize);
            
            List<Test> testList = this.testBusiness.selectTestList(param);
            
            paginationBean.setResult(testList);  // 返回数据结果
            map.put("message",JSON.toJSONString(testList));
        } catch (BaseException e1) {
            map.put("message", e1.getKey());
        } catch (Exception e) {
            logger.error("查询异常" + e.getMessage());
            map.put("message", "查询异常" + e.getMessage());
        }
        return "out";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    @RequestMapping(value = "updateSaveTest.do")
    public String updateSaveTest(@ModelAttribute  Test test, ModelMap map) {
        try {
            if(test == null ){
                // || NumberUtil.isNotPositive(test.getId())){
                    map.put("message","更新对象为空。");
                    return "out";
                }
                int updateCount = this.testBusiness.update(test);
                if(updateCount == 1 ){
                    map.put("message","更新成功。");
                }else{
                    map.put("message","更新失败。");
                }
            } catch (BaseException e1) {
                map.put("message", e1.getKey());
            } catch (Exception e) {
                logger.error("更新异常" + e.getMessage());
                map.put("message", "查询异常" + e.getMessage());
            }
            return "out";
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    @RequestMapping(value = "batchUpdateSaveTest.do")
    public String batchUpdateSaveTest(@ModelAttribute  TestList testList, ModelMap map) {
        try {
            if(testList != null && CollectionUtil.isNotNull(testList.getTestList())){
                int updateCount = this.testBusiness.update(testList.getTestList());
                if(updateCount >0 ){
                    map.put("message","更新成功。");
                }else{
                    map.put("message","更新失败。");
                }
            }
        } catch (BaseException e1) {
            map.put("message", e1.getKey());
        } catch (Exception e) {
            logger.error("批量更新异常" + e.getMessage());
            map.put("message", "批量更新异常" + e.getMessage());
        }
        return "out";
    }

    static class TestList {
        private List<Test> testList;

        public List<Test> getTestList() {
            return testList;
        }

        public void setTestList(List<Test> testList) {
            this.testList = testList;
        }
    }
}